# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from march_shared_msgs/CapturePointPoseRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CapturePointPoseRequest(genpy.Message):
  _md5sum = "efce4fd63555f8abdd034fb55c87e5aa"
  _type = "march_shared_msgs/CapturePointPoseRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Service for getting the position of the capture point, after letting the center of mass falling for time duration (this time can be used to make a step)

float64 duration
"""
  __slots__ = ['duration']
  _slot_types = ['float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       duration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CapturePointPoseRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.duration is None:
        self.duration = 0.
    else:
      self.duration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.duration
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.duration,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.duration
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 8
      (self.duration,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from march_shared_msgs/CapturePointPoseResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class CapturePointPoseResponse(genpy.Message):
  _md5sum = "5b61318011b94ca2af6e372bb1921706"
  _type = "march_shared_msgs/CapturePointPoseResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
float64 duration
geometry_msgs/Pose capture_point


================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['success','duration','capture_point']
  _slot_types = ['bool','float64','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,duration,capture_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CapturePointPoseResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.duration is None:
        self.duration = 0.
      if self.capture_point is None:
        self.capture_point = geometry_msgs.msg.Pose()
    else:
      self.success = False
      self.duration = 0.
      self.capture_point = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B8d().pack(_x.success, _x.duration, _x.capture_point.position.x, _x.capture_point.position.y, _x.capture_point.position.z, _x.capture_point.orientation.x, _x.capture_point.orientation.y, _x.capture_point.orientation.z, _x.capture_point.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.capture_point is None:
        self.capture_point = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 65
      (_x.success, _x.duration, _x.capture_point.position.x, _x.capture_point.position.y, _x.capture_point.position.z, _x.capture_point.orientation.x, _x.capture_point.orientation.y, _x.capture_point.orientation.z, _x.capture_point.orientation.w,) = _get_struct_B8d().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B8d().pack(_x.success, _x.duration, _x.capture_point.position.x, _x.capture_point.position.y, _x.capture_point.position.z, _x.capture_point.orientation.x, _x.capture_point.orientation.y, _x.capture_point.orientation.z, _x.capture_point.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.capture_point is None:
        self.capture_point = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 65
      (_x.success, _x.duration, _x.capture_point.position.x, _x.capture_point.position.y, _x.capture_point.position.z, _x.capture_point.orientation.x, _x.capture_point.orientation.y, _x.capture_point.orientation.z, _x.capture_point.orientation.w,) = _get_struct_B8d().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B8d = None
def _get_struct_B8d():
    global _struct_B8d
    if _struct_B8d is None:
        _struct_B8d = struct.Struct("<B8d")
    return _struct_B8d
class CapturePointPose(object):
  _type          = 'march_shared_msgs/CapturePointPose'
  _md5sum = 'c4ddb84d9f0b8e7beb7aec0ddf05524c'
  _request_class  = CapturePointPoseRequest
  _response_class = CapturePointPoseResponse
