dynamic_controller:
  type: effort_controllers/DirectDynamicController
  joints:
        - left_ankle
        - left_hip_aa
        - left_hip_fe
        - left_knee
        - right_ankle
        - right_hip_aa
        - right_hip_fe
        - right_knee

  links:
        - torso_2_link
        - arm_left_7_link

  Kp:
        - 500
        - 800
        - 1000
        - 2000
        - 6000
        - 70000
        - 150000
  Kv:
        - 50
        - 80
        - 100
        - 100
        - 500
        - 7000
        - 15000
    
  controller_type: "Computed_torque"

  lambda: 0.5