# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from march_shared_msgs/PressureSoleData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PressureSoleData(genpy.Message):
  _md5sum = "f778afef2a62daf4a25bbc0aa80cca01"
  _type = "march_shared_msgs/PressureSoleData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string side
float32 heel_right
float32 heel_left
float32 met1
float32 hallux
float32 met3
float32 toes
float32 met5
float32 arch"""
  __slots__ = ['side','heel_right','heel_left','met1','hallux','met3','toes','met5','arch']
  _slot_types = ['string','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       side,heel_right,heel_left,met1,hallux,met3,toes,met5,arch

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PressureSoleData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.side is None:
        self.side = ''
      if self.heel_right is None:
        self.heel_right = 0.
      if self.heel_left is None:
        self.heel_left = 0.
      if self.met1 is None:
        self.met1 = 0.
      if self.hallux is None:
        self.hallux = 0.
      if self.met3 is None:
        self.met3 = 0.
      if self.toes is None:
        self.toes = 0.
      if self.met5 is None:
        self.met5 = 0.
      if self.arch is None:
        self.arch = 0.
    else:
      self.side = ''
      self.heel_right = 0.
      self.heel_left = 0.
      self.met1 = 0.
      self.hallux = 0.
      self.met3 = 0.
      self.toes = 0.
      self.met5 = 0.
      self.arch = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.side
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8f().pack(_x.heel_right, _x.heel_left, _x.met1, _x.hallux, _x.met3, _x.toes, _x.met5, _x.arch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.side = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.side = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.heel_right, _x.heel_left, _x.met1, _x.hallux, _x.met3, _x.toes, _x.met5, _x.arch,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.side
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8f().pack(_x.heel_right, _x.heel_left, _x.met1, _x.hallux, _x.met3, _x.toes, _x.met5, _x.arch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.side = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.side = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.heel_right, _x.heel_left, _x.met1, _x.hallux, _x.met3, _x.toes, _x.met5, _x.arch,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
