(cl:in-package march_shared_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HIGH_VOLTAGE_ENABLED-VAL
          HIGH_VOLTAGE_ENABLED
          POWER_DISTRIBUTION_BOARD_CURRENT-VAL
          POWER_DISTRIBUTION_BOARD_CURRENT
          HIGH_VOLTAGE_NET_CURRENT-VAL
          HIGH_VOLTAGE_NET_CURRENT
          MASTER_SHUTDOWN_REQUESTED-VAL
          MASTER_SHUTDOWN_REQUESTED
          LOW_VOLTAGE_NETS-VAL
          LOW_VOLTAGE_NETS
          HIGH_VOLTAGE_NETS-VAL
          HIGH_VOLTAGE_NETS
))