// Generated by gencpp from file march_shared_msgs/ChangeComLevel.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_CHANGECOMLEVEL_H
#define MARCH_SHARED_MSGS_MESSAGE_CHANGECOMLEVEL_H

#include <ros/service_traits.h>


#include <march_shared_msgs/ChangeComLevelRequest.h>
#include <march_shared_msgs/ChangeComLevelResponse.h>


namespace march_shared_msgs
{

struct ChangeComLevel
{

typedef ChangeComLevelRequest Request;
typedef ChangeComLevelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeComLevel
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::ChangeComLevel > {
  static const char* value()
  {
    return "744cb9a91acbcc3fd26e43227a65ec3c";
  }

  static const char* value(const ::march_shared_msgs::ChangeComLevel&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::ChangeComLevel > {
  static const char* value()
  {
    return "march_shared_msgs/ChangeComLevel";
  }

  static const char* value(const ::march_shared_msgs::ChangeComLevel&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::ChangeComLevelRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::ChangeComLevel >
template<>
struct MD5Sum< ::march_shared_msgs::ChangeComLevelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::ChangeComLevel >::value();
  }
  static const char* value(const ::march_shared_msgs::ChangeComLevelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::ChangeComLevelRequest> should match
// service_traits::DataType< ::march_shared_msgs::ChangeComLevel >
template<>
struct DataType< ::march_shared_msgs::ChangeComLevelRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::ChangeComLevel >::value();
  }
  static const char* value(const ::march_shared_msgs::ChangeComLevelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::ChangeComLevelResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::ChangeComLevel >
template<>
struct MD5Sum< ::march_shared_msgs::ChangeComLevelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::ChangeComLevel >::value();
  }
  static const char* value(const ::march_shared_msgs::ChangeComLevelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::ChangeComLevelResponse> should match
// service_traits::DataType< ::march_shared_msgs::ChangeComLevel >
template<>
struct DataType< ::march_shared_msgs::ChangeComLevelResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::ChangeComLevel >::value();
  }
  static const char* value(const ::march_shared_msgs::ChangeComLevelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_CHANGECOMLEVEL_H
