// Generated by gencpp from file march_shared_msgs/ContainsGait.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_CONTAINSGAIT_H
#define MARCH_SHARED_MSGS_MESSAGE_CONTAINSGAIT_H

#include <ros/service_traits.h>


#include <march_shared_msgs/ContainsGaitRequest.h>
#include <march_shared_msgs/ContainsGaitResponse.h>


namespace march_shared_msgs
{

struct ContainsGait
{

typedef ContainsGaitRequest Request;
typedef ContainsGaitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ContainsGait
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::ContainsGait > {
  static const char* value()
  {
    return "7b4fecab1a15658a7f1acbd9aa08341f";
  }

  static const char* value(const ::march_shared_msgs::ContainsGait&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::ContainsGait > {
  static const char* value()
  {
    return "march_shared_msgs/ContainsGait";
  }

  static const char* value(const ::march_shared_msgs::ContainsGait&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::ContainsGaitRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::ContainsGait >
template<>
struct MD5Sum< ::march_shared_msgs::ContainsGaitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::ContainsGait >::value();
  }
  static const char* value(const ::march_shared_msgs::ContainsGaitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::ContainsGaitRequest> should match
// service_traits::DataType< ::march_shared_msgs::ContainsGait >
template<>
struct DataType< ::march_shared_msgs::ContainsGaitRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::ContainsGait >::value();
  }
  static const char* value(const ::march_shared_msgs::ContainsGaitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::ContainsGaitResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::ContainsGait >
template<>
struct MD5Sum< ::march_shared_msgs::ContainsGaitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::ContainsGait >::value();
  }
  static const char* value(const ::march_shared_msgs::ContainsGaitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::ContainsGaitResponse> should match
// service_traits::DataType< ::march_shared_msgs::ContainsGait >
template<>
struct DataType< ::march_shared_msgs::ContainsGaitResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::ContainsGait >::value();
  }
  static const char* value(const ::march_shared_msgs::ContainsGaitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_CONTAINSGAIT_H
