// Generated by gencpp from file march_shared_msgs/GetGaitParameters.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETGAITPARAMETERS_H
#define MARCH_SHARED_MSGS_MESSAGE_GETGAITPARAMETERS_H

#include <ros/service_traits.h>


#include <march_shared_msgs/GetGaitParametersRequest.h>
#include <march_shared_msgs/GetGaitParametersResponse.h>


namespace march_shared_msgs
{

struct GetGaitParameters
{

typedef GetGaitParametersRequest Request;
typedef GetGaitParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGaitParameters
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::GetGaitParameters > {
  static const char* value()
  {
    return "7f82cf0d59a91683cea61201da9abbab";
  }

  static const char* value(const ::march_shared_msgs::GetGaitParameters&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::GetGaitParameters > {
  static const char* value()
  {
    return "march_shared_msgs/GetGaitParameters";
  }

  static const char* value(const ::march_shared_msgs::GetGaitParameters&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::GetGaitParametersRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::GetGaitParameters >
template<>
struct MD5Sum< ::march_shared_msgs::GetGaitParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::GetGaitParameters >::value();
  }
  static const char* value(const ::march_shared_msgs::GetGaitParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::GetGaitParametersRequest> should match
// service_traits::DataType< ::march_shared_msgs::GetGaitParameters >
template<>
struct DataType< ::march_shared_msgs::GetGaitParametersRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::GetGaitParameters >::value();
  }
  static const char* value(const ::march_shared_msgs::GetGaitParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::GetGaitParametersResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::GetGaitParameters >
template<>
struct MD5Sum< ::march_shared_msgs::GetGaitParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::GetGaitParameters >::value();
  }
  static const char* value(const ::march_shared_msgs::GetGaitParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::GetGaitParametersResponse> should match
// service_traits::DataType< ::march_shared_msgs::GetGaitParameters >
template<>
struct DataType< ::march_shared_msgs::GetGaitParametersResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::GetGaitParameters >::value();
  }
  static const char* value(const ::march_shared_msgs::GetGaitParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETGAITPARAMETERS_H
