// Generated by gencpp from file march_shared_msgs/GetMoveItTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETMOVEITTRAJECTORYREQUEST_H
#define MARCH_SHARED_MSGS_MESSAGE_GETMOVEITTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <sensor_msgs/JointState.h>

namespace march_shared_msgs
{
template <class ContainerAllocator>
struct GetMoveItTrajectoryRequest_
{
  typedef GetMoveItTrajectoryRequest_<ContainerAllocator> Type;

  GetMoveItTrajectoryRequest_()
    : swing_leg()
    , swing_leg_target_pose()
    , stance_leg_target()  {
    }
  GetMoveItTrajectoryRequest_(const ContainerAllocator& _alloc)
    : swing_leg(_alloc)
    , swing_leg_target_pose(_alloc)
    , stance_leg_target(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _swing_leg_type;
  _swing_leg_type swing_leg;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _swing_leg_target_pose_type;
  _swing_leg_target_pose_type swing_leg_target_pose;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _stance_leg_target_type;
  _stance_leg_target_type stance_leg_target;





  typedef boost::shared_ptr< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMoveItTrajectoryRequest_

typedef ::march_shared_msgs::GetMoveItTrajectoryRequest_<std::allocator<void> > GetMoveItTrajectoryRequest;

typedef boost::shared_ptr< ::march_shared_msgs::GetMoveItTrajectoryRequest > GetMoveItTrajectoryRequestPtr;
typedef boost::shared_ptr< ::march_shared_msgs::GetMoveItTrajectoryRequest const> GetMoveItTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.swing_leg == rhs.swing_leg &&
    lhs.swing_leg_target_pose == rhs.swing_leg_target_pose &&
    lhs.stance_leg_target == rhs.stance_leg_target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace march_shared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90f3814490890f393729ecff105a02dc";
  }

  static const char* value(const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90f3814490890f39ULL;
  static const uint64_t static_value2 = 0x3729ecff105a02dcULL;
};

template<class ContainerAllocator>
struct DataType< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "march_shared_msgs/GetMoveItTrajectoryRequest";
  }

  static const char* value(const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string swing_leg\n"
"geometry_msgs/Pose swing_leg_target_pose\n"
"sensor_msgs/JointState stance_leg_target\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.swing_leg);
      stream.next(m.swing_leg_target_pose);
      stream.next(m.stance_leg_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMoveItTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::march_shared_msgs::GetMoveItTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "swing_leg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.swing_leg);
    s << indent << "swing_leg_target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.swing_leg_target_pose);
    s << indent << "stance_leg_target: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.stance_leg_target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETMOVEITTRAJECTORYREQUEST_H
