// Generated by gencpp from file march_shared_msgs/GetParamString.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETPARAMSTRING_H
#define MARCH_SHARED_MSGS_MESSAGE_GETPARAMSTRING_H

#include <ros/service_traits.h>


#include <march_shared_msgs/GetParamStringRequest.h>
#include <march_shared_msgs/GetParamStringResponse.h>


namespace march_shared_msgs
{

struct GetParamString
{

typedef GetParamStringRequest Request;
typedef GetParamStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParamString
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::GetParamString > {
  static const char* value()
  {
    return "8948cb944b7ffdf0ceea288e1508ccd1";
  }

  static const char* value(const ::march_shared_msgs::GetParamString&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::GetParamString > {
  static const char* value()
  {
    return "march_shared_msgs/GetParamString";
  }

  static const char* value(const ::march_shared_msgs::GetParamString&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::GetParamStringRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::GetParamString >
template<>
struct MD5Sum< ::march_shared_msgs::GetParamStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::GetParamString >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::GetParamStringRequest> should match
// service_traits::DataType< ::march_shared_msgs::GetParamString >
template<>
struct DataType< ::march_shared_msgs::GetParamStringRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::GetParamString >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::GetParamStringResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::GetParamString >
template<>
struct MD5Sum< ::march_shared_msgs::GetParamStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::GetParamString >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::GetParamStringResponse> should match
// service_traits::DataType< ::march_shared_msgs::GetParamString >
template<>
struct DataType< ::march_shared_msgs::GetParamStringResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::GetParamString >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETPARAMSTRING_H
