// Generated by gencpp from file march_shared_msgs/GetParamBool.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETPARAMBOOL_H
#define MARCH_SHARED_MSGS_MESSAGE_GETPARAMBOOL_H

#include <ros/service_traits.h>


#include <march_shared_msgs/GetParamBoolRequest.h>
#include <march_shared_msgs/GetParamBoolResponse.h>


namespace march_shared_msgs
{

struct GetParamBool
{

typedef GetParamBoolRequest Request;
typedef GetParamBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParamBool
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::GetParamBool > {
  static const char* value()
  {
    return "8eb3919de702d426fd0bf3d8e25a33c3";
  }

  static const char* value(const ::march_shared_msgs::GetParamBool&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::GetParamBool > {
  static const char* value()
  {
    return "march_shared_msgs/GetParamBool";
  }

  static const char* value(const ::march_shared_msgs::GetParamBool&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::GetParamBoolRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::GetParamBool >
template<>
struct MD5Sum< ::march_shared_msgs::GetParamBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::GetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::GetParamBoolRequest> should match
// service_traits::DataType< ::march_shared_msgs::GetParamBool >
template<>
struct DataType< ::march_shared_msgs::GetParamBoolRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::GetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::GetParamBoolResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::GetParamBool >
template<>
struct MD5Sum< ::march_shared_msgs::GetParamBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::GetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::GetParamBoolResponse> should match
// service_traits::DataType< ::march_shared_msgs::GetParamBool >
template<>
struct DataType< ::march_shared_msgs::GetParamBoolResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::GetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::GetParamBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETPARAMBOOL_H
