// Generated by gencpp from file march_shared_msgs/GetParamFloatResponse.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETPARAMFLOATRESPONSE_H
#define MARCH_SHARED_MSGS_MESSAGE_GETPARAMFLOATRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace march_shared_msgs
{
template <class ContainerAllocator>
struct GetParamFloatResponse_
{
  typedef GetParamFloatResponse_<ContainerAllocator> Type;

  GetParamFloatResponse_()
    : value(0.0)
    , success(false)  {
    }
  GetParamFloatResponse_(const ContainerAllocator& _alloc)
    : value(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef double _value_type;
  _value_type value;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetParamFloatResponse_

typedef ::march_shared_msgs::GetParamFloatResponse_<std::allocator<void> > GetParamFloatResponse;

typedef boost::shared_ptr< ::march_shared_msgs::GetParamFloatResponse > GetParamFloatResponsePtr;
typedef boost::shared_ptr< ::march_shared_msgs::GetParamFloatResponse const> GetParamFloatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace march_shared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13e23e74b0a02943a0d2f6c5c29a5cd8";
  }

  static const char* value(const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13e23e74b0a02943ULL;
  static const uint64_t static_value2 = 0xa0d2f6c5c29a5cd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "march_shared_msgs/GetParamFloatResponse";
  }

  static const char* value(const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 value\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetParamFloatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::march_shared_msgs::GetParamFloatResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETPARAMFLOATRESPONSE_H
