// Generated by gencpp from file march_shared_msgs/GetParamBoolResponse.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETPARAMBOOLRESPONSE_H
#define MARCH_SHARED_MSGS_MESSAGE_GETPARAMBOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace march_shared_msgs
{
template <class ContainerAllocator>
struct GetParamBoolResponse_
{
  typedef GetParamBoolResponse_<ContainerAllocator> Type;

  GetParamBoolResponse_()
    : value(false)
    , success(false)  {
    }
  GetParamBoolResponse_(const ContainerAllocator& _alloc)
    : value(false)
    , success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetParamBoolResponse_

typedef ::march_shared_msgs::GetParamBoolResponse_<std::allocator<void> > GetParamBoolResponse;

typedef boost::shared_ptr< ::march_shared_msgs::GetParamBoolResponse > GetParamBoolResponsePtr;
typedef boost::shared_ptr< ::march_shared_msgs::GetParamBoolResponse const> GetParamBoolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace march_shared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "906150be8b5d78e2f4adf949da658d02";
  }

  static const char* value(const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x906150be8b5d78e2ULL;
  static const uint64_t static_value2 = 0xf4adf949da658d02ULL;
};

template<class ContainerAllocator>
struct DataType< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "march_shared_msgs/GetParamBoolResponse";
  }

  static const char* value(const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool value\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetParamBoolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::march_shared_msgs::GetParamBoolResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETPARAMBOOLRESPONSE_H
