// Generated by gencpp from file march_shared_msgs/GetParamStringListResponse.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_GETPARAMSTRINGLISTRESPONSE_H
#define MARCH_SHARED_MSGS_MESSAGE_GETPARAMSTRINGLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace march_shared_msgs
{
template <class ContainerAllocator>
struct GetParamStringListResponse_
{
  typedef GetParamStringListResponse_<ContainerAllocator> Type;

  GetParamStringListResponse_()
    : value()
    , success(false)  {
    }
  GetParamStringListResponse_(const ContainerAllocator& _alloc)
    : value(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _value_type;
  _value_type value;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetParamStringListResponse_

typedef ::march_shared_msgs::GetParamStringListResponse_<std::allocator<void> > GetParamStringListResponse;

typedef boost::shared_ptr< ::march_shared_msgs::GetParamStringListResponse > GetParamStringListResponsePtr;
typedef boost::shared_ptr< ::march_shared_msgs::GetParamStringListResponse const> GetParamStringListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator1> & lhs, const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace march_shared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86484fb6c2232a67b7cc08cb94bd25a5";
  }

  static const char* value(const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86484fb6c2232a67ULL;
  static const uint64_t static_value2 = 0xb7cc08cb94bd25a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "march_shared_msgs/GetParamStringListResponse";
  }

  static const char* value(const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] value\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetParamStringListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::march_shared_msgs::GetParamStringListResponse_<ContainerAllocator>& v)
  {
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_GETPARAMSTRINGLISTRESPONSE_H
