// Generated by gencpp from file march_shared_msgs/HighVoltageNet.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_HIGHVOLTAGENET_H
#define MARCH_SHARED_MSGS_MESSAGE_HIGHVOLTAGENET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace march_shared_msgs
{
template <class ContainerAllocator>
struct HighVoltageNet_
{
  typedef HighVoltageNet_<ContainerAllocator> Type;

  HighVoltageNet_()
    : name()
    , operational(false)
    , overcurrent_triggered(false)  {
    }
  HighVoltageNet_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , operational(false)
    , overcurrent_triggered(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _operational_type;
  _operational_type operational;

   typedef uint8_t _overcurrent_triggered_type;
  _overcurrent_triggered_type overcurrent_triggered;





  typedef boost::shared_ptr< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> const> ConstPtr;

}; // struct HighVoltageNet_

typedef ::march_shared_msgs::HighVoltageNet_<std::allocator<void> > HighVoltageNet;

typedef boost::shared_ptr< ::march_shared_msgs::HighVoltageNet > HighVoltageNetPtr;
typedef boost::shared_ptr< ::march_shared_msgs::HighVoltageNet const> HighVoltageNetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator1> & lhs, const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.operational == rhs.operational &&
    lhs.overcurrent_triggered == rhs.overcurrent_triggered;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator1> & lhs, const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace march_shared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9eff07a2a8705cd8361d1a06aead6fe";
  }

  static const char* value(const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9eff07a2a8705cdULL;
  static const uint64_t static_value2 = 0x8361d1a06aead6feULL;
};

template<class ContainerAllocator>
struct DataType< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "march_shared_msgs/HighVoltageNet";
  }

  static const char* value(const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#used in message PowerDistributionBoardState\n"
"string name\n"
"bool operational\n"
"bool overcurrent_triggered\n"
;
  }

  static const char* value(const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.operational);
      stream.next(m.overcurrent_triggered);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HighVoltageNet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::march_shared_msgs::HighVoltageNet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::march_shared_msgs::HighVoltageNet_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "operational: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.operational);
    s << indent << "overcurrent_triggered: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overcurrent_triggered);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_HIGHVOLTAGENET_H
