// Generated by gencpp from file march_shared_msgs/PossibleGaits.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_POSSIBLEGAITS_H
#define MARCH_SHARED_MSGS_MESSAGE_POSSIBLEGAITS_H

#include <ros/service_traits.h>


#include <march_shared_msgs/PossibleGaitsRequest.h>
#include <march_shared_msgs/PossibleGaitsResponse.h>


namespace march_shared_msgs
{

struct PossibleGaits
{

typedef PossibleGaitsRequest Request;
typedef PossibleGaitsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PossibleGaits
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::PossibleGaits > {
  static const char* value()
  {
    return "c219eff76e391465811d4c90e35eb728";
  }

  static const char* value(const ::march_shared_msgs::PossibleGaits&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::PossibleGaits > {
  static const char* value()
  {
    return "march_shared_msgs/PossibleGaits";
  }

  static const char* value(const ::march_shared_msgs::PossibleGaits&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::PossibleGaitsRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::PossibleGaits >
template<>
struct MD5Sum< ::march_shared_msgs::PossibleGaitsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::PossibleGaits >::value();
  }
  static const char* value(const ::march_shared_msgs::PossibleGaitsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::PossibleGaitsRequest> should match
// service_traits::DataType< ::march_shared_msgs::PossibleGaits >
template<>
struct DataType< ::march_shared_msgs::PossibleGaitsRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::PossibleGaits >::value();
  }
  static const char* value(const ::march_shared_msgs::PossibleGaitsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::PossibleGaitsResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::PossibleGaits >
template<>
struct MD5Sum< ::march_shared_msgs::PossibleGaitsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::PossibleGaits >::value();
  }
  static const char* value(const ::march_shared_msgs::PossibleGaitsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::PossibleGaitsResponse> should match
// service_traits::DataType< ::march_shared_msgs::PossibleGaits >
template<>
struct DataType< ::march_shared_msgs::PossibleGaitsResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::PossibleGaits >::value();
  }
  static const char* value(const ::march_shared_msgs::PossibleGaitsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_POSSIBLEGAITS_H
