// Generated by gencpp from file march_shared_msgs/SetGaitVersion.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_SETGAITVERSION_H
#define MARCH_SHARED_MSGS_MESSAGE_SETGAITVERSION_H

#include <ros/service_traits.h>


#include <march_shared_msgs/SetGaitVersionRequest.h>
#include <march_shared_msgs/SetGaitVersionResponse.h>


namespace march_shared_msgs
{

struct SetGaitVersion
{

typedef SetGaitVersionRequest Request;
typedef SetGaitVersionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGaitVersion
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::SetGaitVersion > {
  static const char* value()
  {
    return "31a86c3bd23ebabd9bf6447634f734d0";
  }

  static const char* value(const ::march_shared_msgs::SetGaitVersion&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::SetGaitVersion > {
  static const char* value()
  {
    return "march_shared_msgs/SetGaitVersion";
  }

  static const char* value(const ::march_shared_msgs::SetGaitVersion&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::SetGaitVersionRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::SetGaitVersion >
template<>
struct MD5Sum< ::march_shared_msgs::SetGaitVersionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::SetGaitVersion >::value();
  }
  static const char* value(const ::march_shared_msgs::SetGaitVersionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::SetGaitVersionRequest> should match
// service_traits::DataType< ::march_shared_msgs::SetGaitVersion >
template<>
struct DataType< ::march_shared_msgs::SetGaitVersionRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::SetGaitVersion >::value();
  }
  static const char* value(const ::march_shared_msgs::SetGaitVersionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::SetGaitVersionResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::SetGaitVersion >
template<>
struct MD5Sum< ::march_shared_msgs::SetGaitVersionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::SetGaitVersion >::value();
  }
  static const char* value(const ::march_shared_msgs::SetGaitVersionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::SetGaitVersionResponse> should match
// service_traits::DataType< ::march_shared_msgs::SetGaitVersion >
template<>
struct DataType< ::march_shared_msgs::SetGaitVersionResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::SetGaitVersion >::value();
  }
  static const char* value(const ::march_shared_msgs::SetGaitVersionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_SETGAITVERSION_H
