// Generated by gencpp from file march_shared_msgs/SetParamStringListRequest.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_SETPARAMSTRINGLISTREQUEST_H
#define MARCH_SHARED_MSGS_MESSAGE_SETPARAMSTRINGLISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace march_shared_msgs
{
template <class ContainerAllocator>
struct SetParamStringListRequest_
{
  typedef SetParamStringListRequest_<ContainerAllocator> Type;

  SetParamStringListRequest_()
    : name()
    , value()  {
    }
  SetParamStringListRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetParamStringListRequest_

typedef ::march_shared_msgs::SetParamStringListRequest_<std::allocator<void> > SetParamStringListRequest;

typedef boost::shared_ptr< ::march_shared_msgs::SetParamStringListRequest > SetParamStringListRequestPtr;
typedef boost::shared_ptr< ::march_shared_msgs::SetParamStringListRequest const> SetParamStringListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator1> & lhs, const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator1> & lhs, const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace march_shared_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a20c942da620dbf29654f430aa251492";
  }

  static const char* value(const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa20c942da620dbf2ULL;
  static const uint64_t static_value2 = 0x9654f430aa251492ULL;
};

template<class ContainerAllocator>
struct DataType< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "march_shared_msgs/SetParamStringListRequest";
  }

  static const char* value(const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string[] value\n"
;
  }

  static const char* value(const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetParamStringListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::march_shared_msgs::SetParamStringListRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_SETPARAMSTRINGLISTREQUEST_H
