// Generated by gencpp from file march_shared_msgs/SetParamBool.msg
// DO NOT EDIT!


#ifndef MARCH_SHARED_MSGS_MESSAGE_SETPARAMBOOL_H
#define MARCH_SHARED_MSGS_MESSAGE_SETPARAMBOOL_H

#include <ros/service_traits.h>


#include <march_shared_msgs/SetParamBoolRequest.h>
#include <march_shared_msgs/SetParamBoolResponse.h>


namespace march_shared_msgs
{

struct SetParamBool
{

typedef SetParamBoolRequest Request;
typedef SetParamBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParamBool
} // namespace march_shared_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::march_shared_msgs::SetParamBool > {
  static const char* value()
  {
    return "c7f243f8c6655aded1b4e1f571c7cee3";
  }

  static const char* value(const ::march_shared_msgs::SetParamBool&) { return value(); }
};

template<>
struct DataType< ::march_shared_msgs::SetParamBool > {
  static const char* value()
  {
    return "march_shared_msgs/SetParamBool";
  }

  static const char* value(const ::march_shared_msgs::SetParamBool&) { return value(); }
};


// service_traits::MD5Sum< ::march_shared_msgs::SetParamBoolRequest> should match
// service_traits::MD5Sum< ::march_shared_msgs::SetParamBool >
template<>
struct MD5Sum< ::march_shared_msgs::SetParamBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::SetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::SetParamBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::SetParamBoolRequest> should match
// service_traits::DataType< ::march_shared_msgs::SetParamBool >
template<>
struct DataType< ::march_shared_msgs::SetParamBoolRequest>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::SetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::SetParamBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::march_shared_msgs::SetParamBoolResponse> should match
// service_traits::MD5Sum< ::march_shared_msgs::SetParamBool >
template<>
struct MD5Sum< ::march_shared_msgs::SetParamBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::march_shared_msgs::SetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::SetParamBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::march_shared_msgs::SetParamBoolResponse> should match
// service_traits::DataType< ::march_shared_msgs::SetParamBool >
template<>
struct DataType< ::march_shared_msgs::SetParamBoolResponse>
{
  static const char* value()
  {
    return DataType< ::march_shared_msgs::SetParamBool >::value();
  }
  static const char* value(const ::march_shared_msgs::SetParamBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARCH_SHARED_MSGS_MESSAGE_SETPARAMBOOL_H
