march:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# initialize the controller
  controller:
    trajectory:
      type: model_predictive_trajectory_controller/JointTrajectoryController
      joints:
        - left_ankle
        - left_hip_aa
        - left_hip_fe
        - left_knee
        - right_ankle
        - right_hip_aa
        - right_hip_fe
        - right_knee

    gains:
      left_ankle: {p: 0,  d: 0, i: 0, i_clamp: 0}
      left_hip_aa: {p: 0,  d: 0, i: 0, i_clamp: 0}
      left_hip_fe: {p: 0,  d: 0, i: 0, i_clamp: 0}
      left_knee: {p: 0,  d: 0, i: 0, i_clamp: 0}
      right_ankle: {p: 0,  d: 0, i: 0, i_clamp: 0}
      right_hip_aa: {p: 0,  d: 0, i: 0, i_clamp: 0}
      right_hip_fe: {p: 0,  d: 0, i: 0, i_clamp: 0}
      right_knee: {p: 0,  d: 0, i: 0, i_clamp: 0}


      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

      constraints:
        goal_time: 0.1
        left_ankle:
          trajectory: 0.5
        left_hip_aa:
          trajectory: 0.5
        left_hip_fe:
          trajectory: 0.5
        left_knee:
          trajectory: 0.5
        right_ankle:
          trajectory: 0.5
        right_hip_aa:
          trajectory: 0.5
        right_hip_fe:
          trajectory: 0.5
        right_knee:
          trajectory: 0.5
